---
output:
  xaringan::moon_reader:
    highlightLines: false
    lib_dir: libs
    css: xaringan-themer.css
    nature: 
      countIncrementalSlides: false
      highlightStyle: github
      highlightLines: true
      ratio: 16:10
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(fig.width = 8,fig.height = 6, message = FALSE, warning = FALSE, comment = "", cache = FALSE, fig.retina = 2)
library(flipbookr)
library(xaringan)
library(xaringanthemer)
library(tidyverse)
library(knitr)
library(DT)

ril_link <- "https://raw.githubusercontent.com/ybrandvain/datasets/refs/heads/master/clarkia_rils.csv"
ril_data <- readr::read_csv(ril_link) |>
  dplyr::mutate(growth_rate = case_when(growth_rate =="1.8O" ~ "1.80",
                                          .default = growth_rate),  
                growth_rate = as.numeric(growth_rate),
                visited = mean_visits > 0)
gc_rils <- ril_data |>
  filter(location == "GC", !is.na(prop_hybrid), ! is.na(mean_visits))|>
  select(petal_color, petal_area_mm, num_hybrid, offspring_genotyped, prop_hybrid, mean_visits , asd_mm,visited )|>
  mutate(log10_petal_area_mm = log10(petal_area_mm))
```

```{r xaringan-themer, include=FALSE, warning=FALSE}
library(xaringanthemer)
xaringanthemer::style_duo_accent(
  primary_color = "#ed62ac",
  secondary_color = "#3A5F0B",text_color = "#3A5F0B",title_slide_text_color = "#3A5F0B",
  header_font_google = google_font("Lato"),
  code_font_google   = google_font("Roboto Mono"),
  base_font_size = "22px",
  code_font_size = "1rem",
  text_slide_number_font_size = ".6em")

# Set a global ggplot2 theme
theme_set(
 theme_xaringan( text_font_size = 35  )
)

```

```{r xaringanExtra-share-again, echo=FALSE}
xaringanExtra::use_share_again()
# adds share bar to flipbooks
```



```{css, echo=FALSE}
.left-column, .right-column {
  display: inline-block;
  vertical-align: top;
  width: 46%;
  padding: 0 1%;
}

.left-column pre {
  font-size: 85%;
  max-height: 400px;
  overflow-y: auto;
}
```

**Covariance as the mean of cross products**  

Before breaking this down, I show the whole game: $\Sigma{(X_i-\overline{X})(Y_i-\overline{Y})}/(n-1)$


```{r}
#| eval: false
gc_rils                                                             |>
    filter(!is.na(log10_petal_area_mm), !is.na(prop_hybrid))        |>
    mutate(dev_x = log10_petal_area_mm - mean(log10_petal_area_mm)) |>
    mutate(dev_y       = prop_hybrid - mean(prop_hybrid))           |>
    mutate(cross_prod  = dev_x* dev_y)                              |>
    summarise(sumXprod = sum(cross_prod),
              n        = n(),
              covar    = sumXprod/ (n-1))
```

```{r}
#| echo: false
gc_rils |>
    filter(!is.na(log10_petal_area_mm), !is.na(prop_hybrid))|>
    select(x = log10_petal_area_mm, y = prop_hybrid )|>
    mutate(dev_x = x  -  mean(x))|>
    mutate(dev_y = y  - mean(y))|>
    mutate(cross_prod = dev_x* dev_y)|>
    summarise(sumXprod = sum(cross_prod),
              n        = n(),
              covar    = sumXprod/ (n-1))|>
  kable(digits = 4)
```

---



class: center middle section-slide

# Let's work through this!  




---

**Find means**   


```{r, eval=FALSE}
gc_rils                                                     |>
  filter(!is.na(log10_petal_area_mm),  !is.na(prop_hybrid))|>
  select(x      = log10_petal_area_mm, y = prop_hybrid )   |>
  mutate(mean_x = mean(x))                                 |>
  mutate(mean_x = mean(y)) 
```



```{r,echo=FALSE}
gc_rils |>
  filter(!is.na(log10_petal_area_mm),  !is.na(prop_hybrid))|>
  select(x = log10_petal_area_mm, y = prop_hybrid )|>
  mutate(x = round(x  ,digits = 3))|>
  mutate(mean_x = round(mean(x), digits = 3))|>
  mutate(mean_y = round(mean(y), digits = 3))|>
  relocate(x,mean_x,  y,mean_y) |>
  datatable(options = list(pageLength = 3))
```



---

**Find deviations**   


```{r, eval=FALSE}
gc_rils                                                    |>
  filter(!is.na(log10_petal_area_mm),  !is.na(prop_hybrid))|>
  select(x      = log10_petal_area_mm, y = prop_hybrid )   |>
  mutate(mean_x = mean(x))                                 |>
  mutate(dev_x  = x - mean(x))                             |>
  mutate(mean_x = mean(y))                                 |>
  mutate(dev_y  = y - mean(y))
```



```{r,echo=FALSE}
gc_rils |>
  filter(!is.na(log10_petal_area_mm),  !is.na(prop_hybrid))|>
  select(x = log10_petal_area_mm, y = prop_hybrid )|>
  mutate(x = round(x  ,digits = 3))|>
  mutate(mean_x = round(mean(x)  ,digits = 3))|>
  mutate(dev_x = round(x  -  mean(x),digits = 3))|>
  mutate(mean_y = round(mean(y)  ,digits = 3))|>
  mutate(dev_y = round(y  - mean(y),digits = 3))|>
  relocate(x,mean_x, dev_x, y,mean_y, dev_y ) |>
  datatable(options = list(pageLength = 3))
```


---

**Find cross products**   


```{r, eval=FALSE}
gc_rils                                                    |>
  filter(!is.na(log10_petal_area_mm),  !is.na(prop_hybrid))|>
  select(x      = log10_petal_area_mm, y = prop_hybrid )   |>
  mutate(mean_x = mean(x))                                 |>
  mutate(dev_x  = x - mean(x))                             |>
  mutate(mean_x = mean(y))                                 |>
  mutate(dev_y  = y - mean(y))                             |>
  mutate(cross_prod  = dev_x - dev_y)                       

```



```{r,echo=FALSE}
gc_rils |>
  filter(!is.na(log10_petal_area_mm),  !is.na(prop_hybrid))|>
  select(x = log10_petal_area_mm, y = prop_hybrid )|>
  mutate(x = round(x  ,digits = 3))|>
  mutate(mean_x = round(mean(x)  ,digits = 3))|>
  mutate(dev_x = round(x  -  mean(x),digits = 3))|>
  mutate(mean_y = round(mean(y)  ,digits = 3))|>
  mutate(dev_y = round(y  - mean(y),digits = 3))|>
  relocate(x,mean_x, dev_x, y,mean_y, dev_y ) |>
  mutate(cross_prod  = round(dev_x * dev_y, digits = 4)      )|>
  datatable(options = list(pageLength = 3))
```


---

**Summing cross products**   


```{r, eval=FALSE}
gc_rils                                                    |>
  filter(!is.na(log10_petal_area_mm),  !is.na(prop_hybrid))|>
  select(x      = log10_petal_area_mm, y = prop_hybrid )   |>
  mutate(mean_x = mean(x))                                 |>
  mutate(dev_x  = x - mean(x))                             |>
  mutate(mean_x = mean(y))                                 |>
  mutate(dev_y  = y - mean(y))                             |>
  mutate(cross_prod  = dev_x * dev_y)                      |>
  summarise(sum_cross_prod = sum(cross_prod))

```



```{r,echo=FALSE}
gc_rils |>
    filter(!is.na(log10_petal_area_mm),  !is.na(prop_hybrid))|>
    select(x = log10_petal_area_mm, y = prop_hybrid )|>
    mutate(dev_x = x  -  mean(x))|>
    mutate(dev_y = y  - mean(y))|>
  mutate(cross_prod  = dev_x * dev_y      )|>
  summarise(sum_cross_prod = sum(cross_prod))|>
  kable(digits = 4)
```

---

**Dividing by  $(n - 1)$**   

```{r, eval=FALSE}
gc_rils                                                    |>
  filter(!is.na(log10_petal_area_mm),  !is.na(prop_hybrid))|>
  select(x      = log10_petal_area_mm, y = prop_hybrid )   |>
  mutate(mean_x = mean(x))                                 |>
  mutate(dev_x  = x - mean(x))                             |>
  mutate(mean_x = mean(y))                                 |>
  mutate(dev_y  = y - mean(y))                             |>
  mutate(cross_prod  = dev_x * dev_y)                      |>
  summarise(sum_cross_prod = sum(cross_prod),
            covar = sum_cross_prod / (n()-1))              

```



```{r,echo=FALSE}
gc_rils |>
    filter(!is.na(log10_petal_area_mm),  !is.na(prop_hybrid))|>
    select(x = log10_petal_area_mm, y = prop_hybrid )|>
    mutate(dev_x = x  -  mean(x))|>
    mutate(dev_y = y  - mean(y))|>
  mutate(cross_prod  = dev_x * dev_y      )|>
  summarise(sum_cross_prod = sum(cross_prod),
            covar = sum_cross_prod / (n()-1))  |>
  kable(digits = 4)
```


---



class: center middle section-slide

# *'Fin'*


